#!/bin/bash
#
# This directory contains the files needed to hook an external solver
# to the Ampl modeling environment. This file is part of the OOQP
# distribution.
#
# If this directory doesn't contain a subdirectory named solvers/,
# you should do one of three things
# 
# o Download the extras-ampl.tar.gz file, extract the archive and
#   compile the Ampl solvers library. The archive should be obtainable
#   from the OOQP web site.
#
# o Download the binary (pre-compiled) distribution of this package
#   from the same location. These will generally be named 
#   extras-ampl-bin-???.tar.gz, where ??? is a os-machine identifier.
#
# o Get the master sources directly from the AMPL web site. You may find 
#   these at http://www.ampl.com/cm/cs/what/ampl/hooking.html,
#   or follow the instructions below.
#
# The ampl/solvers directory and files are redistributed with
# permission from the master sources maintained by Lucent
# Technologies. If you downloaded a source distribution, unpack the 
# archive using a sequence of commands similiar to the following
#
#      mv extras-ampl.tar.gz OOQP
#      cd OOQP
#      gunzip extras-ampl.tar.gz
#      tar xvf extras-ampl.tar
# 
# where OOQP is replaced by the name of your OOQP directory. Read the
# file solvers/README for instructions on how to compile the Ampl
# solvers library.
#
# The tar archives suppiled with OOQP were generated using the following 
# commands. First the sources were downloaded from Lucent.

ftp -i -n netlib.bell-labs.com <<EOF
user anonymous $USER@`hostname`
cd /netlib/ampl
get solvers.tar
EOF

# the archive was extracted.

tar xf solvers.tar

# all compressed files within the archive were uncompressed

find solvers -name "*.gz" -exec gunzip -f \{\} \;

# Back up to the parent of extras so that the resulting archive will
# extract in extra/ampl and make the archive
(cd ../../extras/..;\
tar cf extras/ampl/extras-ampl.tar extras/ampl/solvers;\
gzip  -f extras/ampl/extras-ampl.tar)

# Delete solvers.tar and solvers

rm -rf solvers solvers.tar

# That's it.
